export enum Role {
  MEMBER = 'MEMBER',
  ADMIN = 'ADMIN',
  LEADER = 'LEADER',
  SUPER_ADMIN = 'SUPER_ADMIN'
}

export enum EventType {
  REGULAR_DAY = 'REGULAR_DAY',
  SPECIAL_PROGRAM = 'SPECIAL_PROGRAM',
  SUNDAY_PROGRAM = 'SUNDAY_PROGRAM',
  CELEBRATION = 'CELEBRATION',
  GUEST_SESSION = 'GUEST_SESSION',
  INDEPENDENCE_DAY = 'INDEPENDENCE_DAY',
  ONAM = 'ONAM',
  REPUBLIC_DAY = 'REPUBLIC_DAY',
  OTHER = 'OTHER'
}

export enum MediaType {
  VIDEO = 'VIDEO',
  PHOTO = 'PHOTO'
}

export enum MediaPlatform {
  YOUTUBE = 'YOUTUBE',
  FACEBOOK = 'FACEBOOK'
}

export enum TreatStatus {
  PROPOSED = 'PROPOSED',
  APPROVED = 'APPROVED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum NotificationType {
  GENERAL = 'GENERAL',
  EVENT = 'EVENT',
  CELEBRATION = 'CELEBRATION',
  REMINDER = 'REMINDER',
  EMERGENCY = 'EMERGENCY',
  IMPORTANT = 'IMPORTANT'
}
